UCX_MM_SEND_PRE_OVERHEAD=short:40ns,bcopy:220ns
UCX_MM_RECV_OVERHEAD=short:40ns,bcopy:220ns
UCX_IB_SEND_POST_OVERHEAD=common:400ns,zcopy:50ns
UCX_IB_SEND_PRE_OVERHEAD=100ns
UCX_RCACHE_OVERHEAD=360ns
UCX_BCOPY_BW=12000MBps
